### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Enzo2909** [Seeed-Studio/Seeed_Serial_MP3_Player#4]
The code don't work with the IDE arduino. There is too many bugs

**Comment by Cincinnatu** [comment]
Software serial port is used in the example code and requires manual configuration. Alternatively, please provide information regarding any errors encountered.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
