### ISSUE TITLE
Mistake on code to play sd song

### ISSUE THREAD

**Issue by piem4567** [Seeed-Studio/Seeed_Serial_MP3_Player#8]
In the original code Seeed-Studio/Seeed_Serial_MP3_Player/WT2605C_Player.cpp  there is a mistake, to play a song in the sd card, commande is AT+SPLAY=sd0,(filename) and not AT+PLAY=sd0,(filename).

**Comment by Cincinnatu** [comment]
> In the original code Seeed-Studio/Seeed_Serial_MP3_Player/WT2605C_Player.cpp there is a mistake, to play a song in the sd card, commande is AT+SPLAY=sd0,(filename) and not AT+PLAY=sd0,(filename).

Recently, I will verify if the error you mentioned indeed exists.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
